name: SupplyDrop
description: $description
version: '${version}'

main: pixl.dev.supplyDrop.Main
api-version: '1.21'
load: POSTWORLD

authors: [ PixlDev ]

commands:
  supplydrop:
    description: This is the general management command for the SupplyDrop plugin.
    usage: /<command> <start|stop>
    permissions:
      supplydrop.player:
        default: true
      supplydrop.admin:
        default: op